mindmap
  root((Карта решений))
    Стэк Разработки
        Docker
        Nginx Proxy
            Роутер всех встречает
        Laravel 10
            Центральное приложение
        UI
            React
            Bootstrap 5
        MariaDB
            Центральная DB
            Склад Китай
            Склад РФ
            ПВЗ
        Redis
            Кэширующий сервер
        Soketi
            Канал Постоянного соединения
        Minio S3
            Индустриальный Стандарт Файлового хранилища
        Node-red
            Приложение для Складов, ПВЗ
        Test
            Selenuim
            JMeter
    Интернет
        Домен
            Провайдер регистрации
                reg.ru
                nic.ru
            DNS1, DNS2 серверы
            Поддомены
                ns1
                ns2
                www
                api
                mail
                git
        Internet провайдеры
            Cloud
                MTC
                Beeline
                Megaphone
                Sber
                Selectel
            VPS/VDS
                RuVDS
                FirstVDS
        Сторонние провайдеры
            Pay
                Sber эквайринг
                U-money
            Transport
                Почта
                Boxberry
                СДЭК
            OpenID
                vk
                yandex
    Модули
        Сайт
        Клиентский кабинет
        Склад Китай
            Импорт/Экспорт инфы с Центральной DB
            Видят только свою инфу
        Склад РФ
            Уссурийск
            Видят только свою инфу
        ПВЗ
            Блага
            Москва
            Видят только свою инфу
        Приложение для сотрудников
            Менеджеры
            Поддержка
            Отдел Кадров
            Администратор
            Видят всё
        Приложение для разработчиков
            Git
            CI/CD
            Test серверы
