sequenceDiagram
    actor Пользователь

    par Автоматизация процесса оказания услуг
        Пользователь->>Портал: Запрос
    and Портал to 1С
        Note over Пользователь,1С: Паспорт Авторизации

        Портал->>1С: Авторизация
        1С->>Портал: Профиль
        Портал->>Пользователь: Успешно
    end
    par Услуги - Оказанные
        Note over Пользователь,Сервисы: Выбор Списка Услуг
        Пользователь->>Сервисы: Запрос Сервиса
        Note over Сервисы,Процесс: Услуги - Оказанные
        Процесс->>Процесс: Поиск Услуги
        Процесс->>Пользователь: Ответ, Документы

    and Новая Услуга для Пользователя
        Процесс->>Процесс: Новая заявка на услугу

        Note over Сервисы,Процесс: Обработка
        Сервисы->>Процесс: Уведомление
        Процесс->>Процесс: Исполнение
        Процесс->>Процесс: Документ
        Процесс->>Пользователь: Уведомление
        Процесс->>Пользователь: Ответ на услугу
        Note over Процесс,Пользователь: Жизненый цикл оказание услуги
    end

